dependencies {
	implementation project(':BrewCommon')
	implementation 'org.postgresql:postgresql'
	implementation 'io.micrometer:micrometer-tracing-bridge-otel'
	implementation 'io.opentelemetry:opentelemetry-exporter-otlp'
}

springBoot {
	mainClass = 'mx.maleficarum.brewcontrol.BrewControlApplication'
}

test {
	testLogging {
		showStandardStreams = true
	}
	testLogging.showStandardStreams = true
}

jar {
    enabled = true
	manifest {
    	attributes 'Main-Class': 'mx.maleficarum.brewcontrol.BrewControlApplication'
  	}		
}