name: On pull request

on:
    workflow_dispatch:
    pull_request: 
      branches: 
        - development
        - main

jobs:
    plan:
        name: 'Review and Prepare'
        runs-on: 'self-hosted'
        environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0            

            - name: Echo environment
              run: echo "Using environment [${environment}]"
              shell: bash

            - name: 'Looking for GIT Leaks'
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: 'Run tests'
              run: cd ${GITHUB_WORKSPACE}/applications/brewcontrol && ~/.gradle/wrapper/dists/gradle-8.13-bin/5xuhj0ry160q40clulazy9h7d/gradle-8.13/bin/gradle test
              shell: bash
