name: On pull request

on:
    workflow_dispatch:
    pull_request: 
      branches: 
        - development
        - main

jobs:
    plan:
        name: 'Review and Prepare'
        runs-on: 'self-hosted'
        environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0            

            - name: Echo environment
              run: echo "Using environment [${environment}]" && rm -rf /var/folders//rl/bv_t18jj7qsdw4ky9q7jsmhh0000gn/T/gitleaks.tmp
              shell: bash

            - name: 'Looking for GIT Leaks'
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            #- name: 'Run tests'
            #  run: cd ${GITHUB_WORKSPACE}/BrewControl && ~/.gradle/wrapper/dists/gradle-8.13-bin/5xuhj0ry160q40clulazy9h7d/gradle-8.13/bin/gradle test
            #  shell: bash

            - name: 'Build jar'
              run: cd ${GITHUB_WORKSPACE}/BrewControl && ~/.gradle/wrapper/dists/gradle-8.13-bin/5xuhj0ry160q40clulazy9h7d/gradle-8.13/bin/gradle build
              shell: bash
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: ${GITHUB_WORKSPACE}/BrewControl
                push: true
                tags: maleficarum/brewcontrol:latest